version: "3"

services:
  telemetry-frontend:
    build:
      dockerfile: frontend.Dockerfile
      context: ./
    # Copy in changes to the ui, so no need to rebuild the images.
    volumes:
      - /app/node_modules
      - ./packages:/app/packages
    command: yarn start:frontend
    ports:
      - 3000:3000
  telemetry-backend:
    build:
      dockerfile: backend.Dockerfile
      context: ./
    environment:
      - PORT=8000
    ports:
      - 8000:8000
